{{- if .Values.ingress.enabled -}}
{{- $fullName := include "openfoam.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "openfoam.name" . }}
    helm.sh/chart: {{ include "openfoam.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls: 'true'
spec:
  tls:
    - hosts:
      - {{$fullName}}.kcp.kaust.edu.sa
      secretName: kcp-crt
  rules:
    - host: {{$fullName}}.kcp.kaust.edu.sa 
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ $fullName }}
            servicePort: 80
{{- end }}
