apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: openfoam
  name: openfoam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openfoam
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openfoam
    spec:
      containers:
      - name: openfoam
        image:  kcr.kaust.edu.sa/apps/openfoam 
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: kcr-reg
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: openfoam
  labels:
    app: openfoam
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: openfoam
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openfoam
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls: 'true'
spec:
  rules:
  - host: openfoam.kcp.kaust.edu.sa
    http:
      paths:
      - path: /
        backend:
          serviceName: openfoam
          servicePort: 80
  tls:
  - hosts:
    - 'openfoam.kcp.kaust.edu.sa'
    secretName: star-kcp-crt
